name: CompatHelper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: Install CompatHelper
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: Run CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
